version: '3.8'

services:
  calculator-java:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: mvn clean verify
    container_name: java-bad-coverage-tests
